name: Build

on:
  pull_request: {}
  push: { branches: [master, develop, dev/CICD] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
      #  with:
      #    unityVersion: 2020.3.19f1

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2020.3.19f1
          targetPlatform: WebGL 

      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_API_SITE_ID }}
          deploy_alias: ${{ env.BRANCH_NAME }}
          build_directory: 'build/WebGL/WebGL'
          
      # Output 
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      - name: Zip build
        run: |
          pushd build/WebGL
          zip -r ../../WebGL.zip .
          popd

      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: StandaloneWindows64.zip
      #    name: Release ${{ github.ref }}
